services:
  db:
    image: postgres:16
    container_name: backend_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: forum_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  socket:
    image: tranvietkhoa/kforum-backend:latest
    container_name: backend_socket
    ports:
      - "4040:4040"
    environment:
      - REDIS_URL=${REDIS_URL}
      - REDIS_URL_SETUP=${REDIS_URL_SETUP}
      - SOCKET_PORT=${SOCKET_PORT}
      - FRONTEND_ORIGIN=${FRONTEND_ORIGIN}
    depends_on:
      - redis

  redis:
    image: redis:7
    container_name: backend_redis
    restart: always
    ports:
      - "6379:6379"

  backend:
    image: tranvietkhoa/kforum-backend:latest
    container_name: backend_app
    depends_on:
      - db
    environment:
      - PORT=${PORT}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - REDIS_URL=${REDIS_URL}
      - REDIS_URL_SETUP=${REDIS_URL_SETUP}
      - FRONTEND_ORIGIN=${FRONTEND_ORIGIN}
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - "5000:5000"
    restart: always

volumes:
  postgres_data: